export const productos = [
  // CAMISETAS
  {
    id: 1,
    nombre: "Camiseta esqueleto Deportiva",
    descripcion: "Esqueleto Amplio Con Diseño Geométrico, Para Hombre",
    imagen: "https://cdn.pixabay.com/photo/2016/02/16/19/18/man-1203885_960_720.jpg",
    categoria: "Camiseta",
    precio: 89900,
    descuentos: "0.1",
  },
  {
    id: 2,
    nombre: "Camiseta Deportiva Mujer",
    imagen: "https://cdn.pixabay.com/photo/2023/05/08/21/59/woman-7979850_1280.jpg",
    descripcion: "Camiseta Minimalista AEROREADY Train Essentials Cuello Redondo",
    categoria: "Camiseta",
    precio: 109950,
    descuentos: "0.1",
  },
  {
    id: 3,
    nombre: "Camisita Deportiva Hombre",
    imagen: "https://cdn.pixabay.com/photo/2025/06/23/06/50/t-shirt-9675272_1280.jpg",
    descripcion: "Camiseta Training Essentials Holiday Pack",
    categoria: "Camiseta",
    precio: 149950,
    descuentos: "0.15",
  },
  {
    id: 4,
    nombre: "Camisita Deportiva Licra",
    imagen: "https://cdn.pixabay.com/photo/2016/09/21/21/37/sport-1685737_960_720.jpg",
    descripcion: "Camiseta Training Essentials Licra",
    categoria: "Camiseta",
    precio: 159950,
    descuentos: "0.15",
  },

  // PANTALONETAS
  {
    id: 5,
    nombre: "Pantaloneta Deportiva Hombre",
    descripcion: "Pantaloneta Entrenamiento, Para hombre",
    imagen: "https://cdn.pixabay.com/photo/2022/11/26/22/24/athlete-7618566_1280.jpg",
    categoria: "Pantaloneta",
    precio: 98910,
    descuentos: "0.1",
  },
  {
    id: 6,
    nombre: "Pantaloneta Running Hombre",
    imagen: "https://cdn.pixabay.com/photo/2023/10/04/14/15/man-8293794_1280.jpg",
    descripcion: "Pantaloneta tipo running. Para hombre",
    categoria: "Pantaloneta",
    precio: 99900,
    descuentos: "0.1",
  },
  {
    id: 7,
    nombre: "Pantaloneta Running Mujer",
    imagen: "https://cdn.pixabay.com/photo/2024/08/18/13/00/woman-8977930_960_720.jpg",
    descripcion: "Pantaloneta tipo running. Para Mujer",
    categoria: "Pantaloneta",
    precio: 149950,
    descuentos: "0.15",
  },
  {
    id: 8,
    nombre: "Pantaloneta Deportiva Mujer",
    imagen: "https://cdn.pixabay.com/photo/2024/04/10/13/32/woman-8688045_960_720.jpg",
    descripcion: "Pantaloneta Entrenamiento. Para Mujer",
    categoria: "Pantaloneta",
    precio: 149950,
    descuentos: "0.15",
  },

  // TENIS
  {
    id: 9,
    nombre: "Athletic Race H",
    imagen: "t1.jpg",
    descripcion: "Tennis Running Hombre",
    categoria: "Calzado deportivo",
    precio: 225000,
    descuentos: "No disponible",
  },
  {
    id: 10,
    nombre: "Athletic Race M",
    imagen: "t2.jpg",
    descripcion: "Tennis Running Mujer",
    categoria: "Calzado deportivo",
    precio: 225000,
    descuentos: "No disponible",
  },
  {
    id: 11,
    nombre: "Converse Chuck Taylor Heroes",
    imagen: "t3.jpg",
    descripcion: "Tennis Casuales Hombre",
    categoria: "Calzado deportivo",
    precio: 320000,
    descuentos: "No disponible",
  },
  {
    id: 12,
    nombre: "Nike Air Jordan",
    imagen: "t4.jpg",
    descripcion: "Tennis Casuales Hombre",
    categoria: "Calzado deportivo",
    precio: 320000,
    descuentos: "No disponible",
  },
  {
    id: 13,
    nombre: "Meindl Running H",
    imagen: "t5.jpg",
    descripcion: "Tennis Meindl Running Hombre",
    categoria: "Calzado deportivo",
    precio: 260000,
    descuentos: "No disponible",
  },

  // CHAQUETAS
  {
    id: 14,
    nombre: "Rompevientos azul H",
    imagen: "chaqueta1.png",
    descripcion: "Chaqueta rompevientos azul Hombre",
    categoria: "Chaquetas deportivas",
    precio: 110000,
    descuentos: "No disponible",
  },
  {
    id: 15,
    nombre: "Rompevientos vinotinto H",
    imagen: "chaqueta2.jpg",
    descripcion: "Chaqueta rompevientos vinotinto Hombre",
    categoria: "Chaquetas deportivas",
    precio: 110000,
    descuentos: "No disponible",
  },
  {
    id: 16,
    nombre: "Hoodie Badfit negro H",
    imagen: "chaqueta3.jpg",
    descripcion: "Hoodie Badfit negro Hombre",
    categoria: "Chaquetas deportivas",
    precio: 180000,
    descuentos: "No disponible",
  },
  {
    id: 17,
    nombre: "Chaqueta casual caqui H",
    imagen: "chaqueta4.jpg",
    descripcion: "Chaqueta casual caqui Hombre",
    categoria: "Chaquetas deportivas",
    precio: 230000,
    descuentos: "No disponible",
  },
  {
    id: 18,
    nombre: "Chaqueta beisbolera H",
    imagen: "chaqueta5.jpg",
    descripcion: "Chaqueta beisbolera New York Yankees Hombre",
    categoria: "Chaquetas deportivas",
    precio: 380000,
    descuentos: "No disponible",
  }
];
