export const tenis = [{
    nombre: "Athletic Race H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\t1.jpg",
    descripcion: " Tennis Running Hombre",
    categoria: "Calzado deportivo",
    precio: 225000,
    descuentos: "No disponible",
},
{
    nombre: "Athletic Race M",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\t2.jpg",
    descripcion: "Tennis Runnig Mujer",
    categoria: "Calzado deportivo",
    precio: 225000,
    descuentos: "No disponible",
},
{
    nombre: "Converse Chuck Taylor Heroes",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\t3.jpg",
    descripcion: "Tennis Casuales Hombre",
    categoria: "Calzado deportivo",
    precio: 320000,
    descuentos: "No disponible",
},
{
    nombre: "Nike Air Jordan",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\t4.jpg",
    descripcion: "Tennis Casuales Hombre",
    categoria: "Calzado deportivo",
    precio: 320000,
    descuentos: "No disponible",
},
{
    nombre: "Meindl Running H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\t5.jpg",
    descripcion: "Tennis Meindl Running Hombre",
    categoria: "Calzado deportivo",
    precio: 260000,
    descuentos: "No disponible",
}
]
export const chaquetas = [{
    nombre: "Rompevientos azul H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\chaqueta1.png",
    descripcion: "Chaqueta rompevientos azul Hombre",
    categoria: "Chaquetas deportivas",
    precio: 110000,
    descuentos: "No disponible",
},
{
    nombre: "Rompevientos vinotinto H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\chaqueta2.jpg",
    descripcion: "Chaqueta rompevientos vinotinto Hombre",
    categoria: "Chaquetas deportivas",
    precio: 110000,
    descuentos: "No disponible",
},
{
    nombre: "Hoodie Badfit negro H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\chaqueta3.jpg",
    descripcion: "Hoodie Badfit negro Hombre",
    categoria: "Chaquetas deportivas",
    precio: 180000,
    descuentos: "No disponible",
},
{
    nombre: "Chaqueta casual caqui H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\chaqueta4.jpg",
    descripcion: " Chaqueta casual caqui Hombre",
    categoria: "Chaquetas deportivas",
    precio: 230000,
    descuentos: "No disponible",
},
{
    nombre: "Chaqueta beisbolera H",
    imagen: "C:\Users\German-Cruz\OneDrive\Escritorio\generation\Hackaton-Tienda-Deportiva\utils\images\chaqueta5.jpg",
    descripcion: " Chaqueta beisbolera New York Yankees Hombre",
    categoria: "Chaquetas deportivas",
    precio: 380000,
    descuentos: "No disponible",
}
]
